Module: SmartSql.Starter
Author: Ahoo Wang
Mode: Util
CodeFileInfo:
  - Path:
      "{0}": "Erp.Amazon.Models\\StatisticalAnalysis\\ProfitRate"
      "{0}Repository": "Erp.Amazon.Repositories\\Implement\\StatisticalAnalysis\\ProfitRate"
      "I{0}Repository": "Erp.Amazon.Repositories\\Interface\\StatisticalAnalysis\\ProfitRate"
    ProjectName: "amazon"
    ProjectPath: "D:\\Project\\erpamazonworker"

