Module: SmartSql.Starter
Author: xiw
Mode: Uilt

# 构建任务
Build:
  
  #  ClearDir:
  #    Type: Clear
  #    Parameters:
  #      Dirs: '.'

  MakeBuildDir:
    Type: Process
    Parameters:
      FileName: powershell
      Args: mkdir '{{Project.Parameters.BuildDir}}'
  Copy:
    Type: Process
    Parameters:
      FileName: powershell
      Args:  cp '{{Project.ConfigPath}}' '{{Project.Parameters.BuildDir}}'
